[project]
name = "4Charm"
version = "5.2.2"
description = "4Charm - Advanced 4chan Media Downloader"
authors = [
    {name = "RazorBackRoar"}
]
requires-python = ">=3.9"


[tool.setuptools.packages.find]
where = ["src"]
include = ["four_charm*"]
